### ISSUE TITLE
Support for SCRIPT_NAME

### ISSUE THREAD

**Issue by fwolfst** [epistemonikos/wsgi-language-middleware#1]
Hi,

I'd like to see an addition to (optionally) modify `SCRIPT_NAME`, such that `h.url()` automatically prepends the generated URLs with the given locale.

I have a prepared a prototype for that, might send a PR when internal tests are green for that and you agree.

Thanks,
Felix

**Comment by dperezrada** [comment]
Hi @fwolfst,
Great to hear you have a pull request almost there.
I think make sense to have a method that gives you the url with the given locale.

Best
Daniel

**Comment by fwolfst** [comment]
I am a bit single-eyed with my issues, as I am on a pylons project. I assumed `SCRIPT_NAME` is wsgi-standard (and it is), but `h.url()` is definately not (we use it in pylons).

**Comment by dperezrada** [comment]
I just merged the pull request, also updated the pypi repository with version 0.4
Thanks ;)
