### ISSUE TITLE
Make the gettext-install optional

### ISSUE THREAD

**Issue by fwolfst** [epistemonikos/wsgi-language-middleware#2]
Hi,

Apparently in multi-threaded webservers, `gettext.install` is an expensive operation. I'd like that part to be optional. In our case, translations are pre-fetched If I understand correctly, and the translator could then be changed in a `BaseController`.

Would be happy to hear your opinion on that matter, I might be able to create a PR for that.

Thanks and have fun
Felix

**Comment by dperezrada** [comment]
Yes, gettext.install is expensive. Let's make install optional.

What do you mean you have pre-fetched translations?

Best,
Daniel

**Comment by dperezrada** [comment]
Thanks for the pull request.
I already did the merge.

;)
